create table IF NOT EXISTS public."users" (
  id bigint generated by default as identity not null,
  "firstName" VARCHAR not null,
  "lastName" VARCHAR not null,
  email character varying not null,
  password character varying not null,
  created_at timestamp with time zone not null default now(),
  updated_date timestamp with time zone null,
  constraint Users_pkey primary key (id),
  constraint Users_email_key unique (email),
  constraint valid_email check (
    (
      (email)::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text
    )
  )
) TABLESPACE pg_default;

create index IF not exists email_users on public."users" using btree (email) TABLESPACE pg_default;
